### ISSUE TITLE
[Unit Test Refactoring] Check tests that were @Ignore'd because of EmfCompareUtil flaws

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eMoflon/emoflon#109]
```
See title.
```

Original issue reported on code.google.com by `roland.k...@googlemail.com` on 1 Jul 2014 at 12:29

**Comment by anthonyanjorin** [comment]
We should just delete such tests as they are useless

**Comment by anthonyanjorin** [comment]
This doesn't seem to be a problem anymore - if a test becomes red for some reason, and if this due to EMFCompare, then we should just delete the test.
