### ISSUE TITLE
[MOSL] Progress monitoring for MOSL unparser

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eMoflon/emoflon#134]
```
Please perform some basic progress monitoring in conversion to MOSL so the user 
has a rough feeling for how long the process will take and what the current 
status is.

Use the eclipse ProgressMonitor passed into the action.
```

Original issue reported on code.google.com by `tonyAnjo...@googlemail.com` on 13 Aug 2014 at 2:07

**Comment by RolandKluge** [comment]
@SchroedingersCatIsUndead Would be a good opportunity for you to get in touch with Eclipse plugin development. Do not hesitate to ask me about what to do. :-)
