### ISSUE TITLE
Rule priorities, rule layers, optional create for TGGs?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eMoflon/emoflon#156]
```
Even though pure TGGs should not contain rule priorities, it would be nice to 
be abble to define "rule priorities" using visual syntax.

Currently, this can only be achieved by using NACs (quite error prone, I guess) 
or by extending TGGLanguage.algorithm.configurator.impl.ConfiguratorImpl.

The second choice exposes too many implementation details, though.
```

Original issue reported on code.google.com by `roland.k...@googlemail.com` on 2 Sep 2014 at 6:38

**Comment by RolandKluge** [comment]
@anthonyanjorin @erhanleblebici Is this a valid issue? Please close if not.

**Comment by anthonyanjorin** [comment]
A new idea in this direction is to allow the user to define "layers" of rules.  All matches of rules in a higher layer are handled before any matches of lower layers.  This extra source of information can further help avoiding dead-ends during the transformation.

**Comment by anthonyanjorin** [comment]
This might also be related to supporting "optional create" @erhanleblebici

**Comment by anthonyanjorin** [comment]
These features are still missing and are quite important/relevant.

**Comment by RolandKluge** [comment]
Issue moved to [eMoflon/emoflon-tool #4](https://github.com/eMoflon/emoflon-tool/issues/4) via [**ZenHub**](https://www.zenhub.com/)
