### ISSUE TITLE
[EA] Introduce EnumExpression

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eMoflon/emoflon#242]
```
We currently, treat enum constants as LiteralExpresssions. Unfortunately, there 
is no dialog/drop-down to select from all possible enum constants.

This is dangerous because a string representation will not reflect changes to 
enum/package names!
```

Original issue reported on code.google.com by `roland.k...@googlemail.com` on 23 Oct 2014 at 10:19

**Comment by RolandKluge** [comment]
The current situation is that we will not spent so much effort into a feature of EA that will require a whole 'transformation process' from LiteralExpression to the new EnumExpressions.

Still, it would be nice to find out how to efficiently refactor EEnums.
