### ISSUE TITLE
SpecificationPackage.CONSTRAINT_OPERATION_COUNT Problem

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eMoflon/emoflon#244]
```
Some problems with 
SpecificationPackage.CONSTRAINT_OPERATION_COUNT
EMFTypePackage.EMF_CONSTRAINT_OPERATION_COUNT

in democles related .jar files
```

Original issue reported on code.google.com by `f.deckwe...@googlemail.com` on 23 Oct 2014 at 12:37

**Comment by anthonyanjorin** [comment]
not sure if this is still current

**Comment by RolandKluge** [comment]
Is this issue still valid? If yes, how can it be validated?

**Comment by anthonyanjorin** [comment]
uff - have no idea what this was/is :(  @fdeckwerth?

**Comment by fdeckwerth** [comment]
Ich auch nicht

Von: anthonyanjorin [mailto:notifications@github.com]
Gesendet: Dienstag, 17. November 2015 11:52
An: eMoflon/emoflon
Cc: Frederik Deckwerth
Betreff: Re: [emoflon] SpecificationPackage.CONSTRAINT_OPERATION_COUNT Problem (#244)


uff - have no idea what this was/is :( @fdeckwerth<https://github.com/fdeckwerth>?

**Comment by RolandKluge** [comment]
Alright - seems to be no show stopper. I close this issue for now.
