### ISSUE TITLE
[EA] An EAttribute may not be named "href"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eMoflon/emoflon#280]
```
Write a validation rule

@Alex, you are just in cc, I assign this task to myself
```

Original issue reported on code.google.com by `erhanleb...@hotmail.com` on 21 Nov 2014 at 9:24

**Comment by RolandKluge** [comment]
Is this issue still valid?

**Comment by RolandKluge** [comment]
This issue was moved to eMoflon/emoflon-tool#6
