### ISSUE TITLE
[Handbook] Document how to correctly create and use ENUMs in EA

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eMoflon/emoflon#328]
```
We need to have a short section in Part 6 of our handbook explaining how to 
create and use ENUMS correctly with our EA Addin.

We could also explain here special things such as:

- support for interfaces
- usage of Alias (Datatypes mapped to arbitrary types)
- ...?
```

Original issue reported on code.google.com by `tonyAnjo...@googlemail.com` on 11 Feb 2015 at 3:38

**Comment by RolandKluge** [comment]
I have added a section for the visual syntax (Part VI, last section).

@SchroedingersCatIsUndead Could you write the analogous part for MOSL?

**Comment by RolandKluge** [comment]
The "MOSL part" no longer applies - closing this issue.
