### ISSUE TITLE
Reserved keywords in TGG rules

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#360]
"csp" is a reserved keywords for TGGs and should not be used in rules.

This should be checked as a validation rule in EA.

**Comment by anthonyanjorin** [comment]
A better solution would be to use "__csp__" as the name of the csp object variable in our generated SDMs, instead of the current "csp", which can easily clash with names used by a TGG developer (this just happened to me).

**Comment by RolandKluge** [comment]
This issue was moved to eMoflon/emoflon-tool#7
