### ISSUE TITLE
All plugin IDs should start with org.moflon...

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#372]
All eMoflon plugins should start with the same prefix, making it easier to sort/identify/delete/... all plugins together.

Several plugins already implement this convention.

**Comment by RolandKluge** [comment]
I tried the renaming procedure today for MoflonBackend but failed greatly: After renaming "DotToSDMLanguage" to "org.moflon.ide.visualization.sdm", the IntegrationBuilder went into an infinite loop. The status messages make me think that somewhere inside the builder the handling of names that contain dots is not fully working yet because the builder went on creating and destroying the generated artefacts in the /model directory over and over again, ending up in an infinite loop.

**Comment by anthonyanjorin** [comment]
Interesting ...  Especially as I have already tried this and fixed a few bugs for our PG visualisation (which is already named according to our new conventions).  I was hoping this would just work.

**Comment by RolandKluge** [comment]
That's right. Probably it has something to do with cross-project dependencies.
One annoying thing is that references to classes in TGG CSPs are not updated when a package is renamed.

**Comment by RolandKluge** [comment]
As a first step, I renamed all non-generated projects to have the same project name, plugin ID and last SVN path segment. Tests  are green.

AttributeConstraintDemoclesCodeGenerator  -->  org.moflon.sdm.constraints.codegenerator
CheatSheetTutorial  -->  org.moflon.tutorial
CodeGen2  -->  org.moflon.sdm.codegen2 (de.uni_kassel.fujaba.codegen)
DemoclesCodeGenerator  -->  org.moflon.sdm.compiler.democles
DemoclesPatternMatcher  -->  org.moflon.sdm.democles.patternmatcher
Ecore2FujabaTransformation  -->  org.moflon.sdm.codegen2.ecore2fujaba
Linkbrowser  -->  org.moflon.ide.visualization.linkbrowser (de.fhg.iao.Linkbrowser)
MOFLON2EAEcoreAddin  -->  org.moflon.ide.eaaddin
MoflonIdeFeature  -->  org.moflon.deployment.feature
MoflonAutoTestPlugin  -->  org.moflon.testing.autotester
MoflonIdeUi org.moflon.ide.ui
MoflonPDEFragment  -->   org.moflon.deployment.pdefragment
MoflonTestingFramework  -->  org.moflon.testing.testframework
MoflonTextEditorFramework  -->   org.moflon.ide.editor
MoflonValidationPlugin  -->  org.moflon.validation.validationplugin
ReverseLinkNavigationDemoclesCodeGenerator  -->   org.moflon.sdm.controlflow.reversenavigation
SDMCompiler  -->  org.moflon.sdm.compiler.eclipse

**Comment by anthonyanjorin** [comment]
@anthonyanjorin

**Comment by anthonyanjorin** [comment]
How about now renaming all metamodel projects?  That should work right?  Should I look into renaming the project that caused problems mentioned above?

**Comment by RolandKluge** [comment]
That's right. Renaming MM projects should work fine. It would be great if you could check that.

**Comment by anthonyanjorin** [comment]
Have now renamed all MM projects.

I'll start trying a few projects next.

**Comment by anthonyanjorin** [comment]
The namespace org.moflon.tgg.* is now completed.

**Comment by anthonyanjorin** [comment]
What is remaining:

* DepthFirstSearchGraph (should be easy)
* Moca (should be easy)
* MocaToMoflonTransformation (already tried, for some reason very problematic!)
* MocaTree (probably very problematic)
* MoflonPropertyContainer (extremely problematic - all property files will be invalidated)
* AttributeConstraintScopeValidation
* AttributeConstraintToDemocles
* ControlFlow
* DemoclesAttributeConstraints
* DemoclesAttributeConstraintSpecification
* LiteralExprResolver
* ScopeValidation
* SDMLanguage
* SDMLanguageToDemocles
* Sequencer
* ValidationResult

**Comment by RolandKluge** [comment]
One project has not been renamed correctly: 
org.moflon.compiler.sdm.democles should be org.moflon.sdm.compiler.democles

**Comment by RolandKluge** [comment]
Thank you, Tony, for tackling the next bunch of projects.

Could you also correct the following project, whose name is currently not correct:
org.moflon.compiler.sdm.democles should be org.moflon.sdm.compiler.democles

**Comment by anthonyanjorin** [comment]
org.moflon.sdm.compiler.democles is now named correctly (was just the PSF thankfully)

**Comment by anthonyanjorin** [comment]
Some bad smells:  any "additional dependencies" are worrying and actually shouldn't be necessary.  

E.g., DemoclesAttributeConstraintToDemocles depends on org.moflon.sdm.compiler.democles.validation.result like this and I don't understand why.

@fdeckwerth?

**Comment by anthonyanjorin** [comment]
uff...  one of the projects had a checked in genmodel with some manual changes.  Took me a while to spot that.  We should introduce a way to specify such genmodel options in our metamodels (or at least the project property file or something similar).

**Comment by anthonyanjorin** [comment]
problematic project is now called org.moflon.sdm.constraints.democles

For some reason these setting are needed - not really a problem as EMF is so flexible but I have now added a README in the /model folder so its not that easy to miss.

**Comment by anthonyanjorin** [comment]
What is now left:

* MocaTree
* MoflonPropertyContainer
* ControlFlow
* LiteralExprResolver 
* ScopeValidation
* SDMLanguage
* SDMLanguageToDemocles
* Sequencer

I'm not sure if we really want to rename MocaTree and MoflonPropertyContainer.  All our users will be quite pissed I can imagine if we don't have an automated update mechanism.  Let's discuss that again when everything else is done.

**Comment by anthonyanjorin** [comment]
Just a comment:  For the handling of attribute constraints we load a "builtInLibraryModel.xmi".  This is extremely problematic as URIs and the location of this model is hard coded as strings.

**Comment by anthonyanjorin** [comment]
Please remember to inform me here if anyone else is working on renaming

**Comment by anthonyanjorin** [comment]
What is now left:

* MocaTree
* MoflonPropertyContainer
* ControlFlow
* SDMLanguage

**Comment by anthonyanjorin** [comment]
Now only three nasty projects are left:
* MocaTree
* MoflonPropertyContainer
* SDMLanguage

I suggest we carry on with the actual modularisation before revisiting these projects.  SDMLanguage should at least then be easier to fix after restructuring our EAP files.

**Comment by RolandKluge** [comment]
From my perspective, SDMLanguage is not worth the effort because it will get killed in the mid future.

I will open up a separate issue for MocaTree.
