### ISSUE TITLE
Transmission of validation errors to EA

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#383]
This is a great feature when it works and is really helpful when searching for validation problems.

There are, however, still two problems:

1.  Sometimes EA freezes and has to be killed.  I guess something has to be made more robust here.
2.  Only some error "types" get transmitted, many others do not make it over to EA

Would be great to invest some energy into getting this working in a reliable manner.

**Comment by RolandKluge** [comment]
I would like to add a concrete example: https://github.com/eMoflon/emoflon-issue-tracking-system/blob/master/issuefiles/issue383__nondeterministic_transfer_of_validation_errors.zip

The contained Ecore file contains a number of validation errors (see *validation_errors_in_Eclipse.txt*), but only some of them make it to EA (see *validation_errors_in_EA.png*). Strangely, some more validation errors appear after pressing "Validate All".

**Comment by RolandKluge** [comment]
I could partly reproduce this issue with the current state of the Zoo 1 test workspace: There are some warnings in Eclipse (concerning duplicate outgoing activity edges etc.), but I am unsure whether they should be transfered to EA.

@gervarro Should validation warnings also be transfered to EA?

**Comment by RolandKluge** [comment]
OK, not so important - I close this issue.
