### ISSUE TITLE
[Democles] improve attribute checks with constants

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#387]
Currently, Democles generates code such as this:

 if (isInterfacevalue.equals("true")) {
	String isInterfacename = isInterface.getName();
	if (isInterfacename.equals("isInterface")) {
		return new Object[] { isInterface, eClassNode, classInPackage };
	}
}

The problem with this is attribute values CAN be null (this happens constantly - I tried it out) and the pattern matcher jumps out with an NPE terminating prematurely.

It would be better to test in "Yoda" style as follows:

if ("true".equals(isInterfacevalue)) {
	String isInterfacename = isInterface.getName();
	if ("isInterface".equals(isInterfacename)) {
		return new Object[] { isInterface, eClassNode, classInPackage };
	}
}

**Comment by gervarro** [comment]
Attribute lookup should be switched from BF -> BB to BF -> BU in the future to enforce null and type check on variables.

**Comment by RolandKluge** [comment]
This issue was moved to eMoflon/emoflon-tool#8
