### ISSUE TITLE
Add a demo for TGGs

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#402]
Would it be sensible to have a demo project for TGGs?

We could even extend the current demo project with a TGG that translates a double-linked list into a single-linked list.

**Comment by anthonyanjorin** [comment]
Our demo workspace is now available as a normal "workspace" just like all the other test workspaces.

The idea here would be to add a simple "hello world" TGG and a few JUnit-Tests that make sure that batch and sync are working after a user installs eMoflon.

**Comment by RolandKluge** [comment]
This issue was moved to eMoflon/emoflon-tool#10
