### ISSUE TITLE
[EA] Creating a copy of statement nodes or method call expressions leads does not work correctly.

### ISSUE THREAD

**Issue by Arikae** [eMoflon/emoflon#440]
This bug occurs when I try to copy a statement node or an object variable that has been bound by a method call expression.
After creating the copy, these method call expressions don't have informations about their parameter types anymore. 
At the moment this is fixed by reselecting the underlying method, which resets the original parameter types but also resets their values to null.

**Comment by SchroedingersCatIsUndead** [comment]
This is impossible, becauseof the intern ID system.

When you create foo(bar) the parameter bar is create with a new ID. When you use copy from EA it copies with the ID and 2 Parameters with the same ID are not allowed, so the new one is set to NULL. This is provided from EA and not from our Add-in
