### ISSUE TITLE
The manipulation of manifest.mf and plugin.xml files should be independent of the SDM compiler

### ISSUE THREAD

**Issue by gervarro** [eMoflon/emoflon#441]
It would be nice to remove the 'org.moflon.ide.plugins' dependency from the SDM compiler (i.e., 'org.moflon.codegen.eclipse' plugin).

**Comment by RolandKluge** [comment]
The dependency cannot be removed currently. 

There were two places were the org.moflon.ide.plugins is used:
* **NewMonitoredMetamodelLoader** PluginURIToResourceURIRemapper was used - I commented it. Please see if you can instantiate the mapping elsewhere.
* **MoflonCodeGenerator** I would suggest to execute the code that is currently marked as step (7) and (8) inside MoflonCodeGenerator to locations that call the code generator: such as 'org.moflon.codegen.eclipse.ui.Generate'. However, 'org.moflon.codegen.eclipse.ui.Generate' is inside the plugin 'org.moflon.codegen.eclipse' and needs to be moved to an appropriate UI project. before --> @gervarro

**Comment by RolandKluge** [comment]
Done.
