### ISSUE TITLE
[Validation] Validation log in Eclipse is missing due to consolidated validation process

### ISSUE THREAD

**Issue by gkulcsar** [eMoflon/emoflon#442]
Now, the classes MonitoredSDMValidator and RepositoryCodeGenerator implement the exact same validation process. At the moment, the logging is commented out as the two classes originally had separate loggers. It has to be investigated if they make a difference and introduce a common logger.

**Comment by RolandKluge** [comment]
This issue was moved to eMoflon/emoflon-tool#11
