### ISSUE TITLE
[EA] View for MethodCallExpressions

### ISSUE THREAD

**Issue by SchroedingersCatIsUndead** [eMoflon/emoflon#460]
The old View in a GridSystem is more clearly
![eaparametervaluesbefore](https://cloud.githubusercontent.com/assets/9741282/8182471/f7a34e3c-142f-11e5-9cdd-c1a27d094616.png)

in the new View of EA is it hard to see for which parameter the argument will be given.
![screenshot 2015-06-16 13 56 41](https://cloud.githubusercontent.com/assets/9741282/8182556/b3e66aac-1430-11e5-8b3d-7c4456d3d751.png)

If possible turn the view back, please

**Comment by anthonyanjorin** [comment]
The new view has its advantages ...  I would suggest adding the name of the argument as extra information to the new view. Perhaps something like:

----  "objectVariable" => nameOfAttribute : EString
|
----  "typeGuid" => newNameOfAttribute : EString

?

**Comment by SchleichAlex** [comment]
syntax is now: "<value>" => <parameter name> : <parameter type>

**Comment by RolandKluge** [comment]
Is this resolved now from your perspective @SchroedingersCatIsUndead ?

**Comment by RolandKluge** [comment]
Closing this issue for now.
