### ISSUE TITLE
SDM generation - EdgeGuard.NONE broken?

### ISSUE THREAD

**Issue by Arikae** [eMoflon/emoflon#465]
When generating a SDM where an Activity Edge has been set to Edgeguard.NONE, the edge will simply disappear.
Ommiting the guard value and taking the standardvalue seems nonetheless to work somehow.

**Comment by RolandKluge** [comment]
Could you check whether this bug persists?
If yes, an example would help very much!

**Comment by gervarro** [comment]
Could you please explain me what the actual problem is? We have never generated code for activity edges.

**Comment by Arikae** [comment]
Well then maybe this problem has already been fixed.
Until next tuesday I'm in a bit of stress because of some upcoming exams, but then I'll try to test it again.

The initial problem was simply that if I generate a new SDM where two Activity nodes are connected with an ActivityEdge, then what would happen is that the edge would disappear when I set the guard to EdgeGuard.NONE. When ommiting this and solely creating the plain ActivityEdge-objectvariable without setting the guard, the Edge would be generated correctly.

But I'll recheck on that

**Comment by gervarro** [comment]
No hurry.
I simply did not and still do not understand what the problem is exactly. However, I would share the information with you that an empty activity node with an outgoing unguarded (NONE) edge is ignored in the code generation process as it does not represent any meaningful behaviour.

**Comment by Arikae** [comment]
Ah the problem was a bit more serious.
The codegenerator would throw an exception because of this "missing" edge since it would separate the complete control flow of the activity and lead to unreachable AcitivityNodes.

**Comment by RolandKluge** [comment]
This issue was moved to eMoflon/emoflon-tool#15
