### ISSUE TITLE
[TGG] Optimize siblings heuristic

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#486]
Our siblings heuristic when picking the next set of matches in the readySet is currently costly.

As it is really important for many TGGs (not only with amalgamation) it would make sense to invest some time to understand why it is so costly and how we can speed it up.  An idea would be to introduce counters, a table, or some other form of bookkeeping, so that the check does not need to be repeated all the time.

**Comment by RolandKluge** [comment]
This issue was moved to eMoflon/emoflon-tool#18
