### ISSUE TITLE
[Docu] Document typical eMoflon tasks in the handbook

### ISSUE THREAD

**Issue by jbuerdek** [eMoflon/emoflon#489]
Add step-by-step descriptions and best-practices to the handbook.
For instance:
- step-by-step: building SDMs/Meta-models after changes
- best-practices: how to handle lists in SDMs

**Comment by RolandKluge** [comment]
@erhanleblebici @gervarro

**Comment by RolandKluge** [comment]
I have now described how to run EA as the notorious "Second Windows User": https://github.com/eMoflon/emoflon-issue-tracking-system/wiki/Using-EA-With-A-Second-Windows-Account

**Comment by RolandKluge** [comment]
Concerning best practices: I have created a separate issue (#595) for the handling of lists.

Since this is a generic issue, I close this one.
