### ISSUE TITLE
[Handbook] Document eMoflon development workflow

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#492]
I guess it would be a good idea to write down the development workflow (automatic tests, bootstrapping) to allow new eMoflon developers and students working on eMoflon to start more quickly.

The question is whether to place this in the Wiki or in the handbook. I would prefer the Wiki.

@erhanleblebici @anthonyanjorin @gervarro

**Comment by anthonyanjorin** [comment]
We already have something like this in the old wiki (setting up an eMoflon workspace).  Might be a good idea to move it to the new wiki here.

**Comment by RolandKluge** [comment]
Do You mean the Google Code wiki?

**Comment by anthonyanjorin** [comment]
No - foswiki (that was only internally accessible)

**Comment by RolandKluge** [comment]
This is ongoing work here: https://github.com/eMoflon/emoflon/wiki/Developer-Resources
