### ISSUE TITLE
[TGG] Document means of persisting input precedence graph

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#501]
Via our Configurator interface, it is now pretty easy to persist the input precedence graph in its state before the translation phase begins.

This is cool if you want to inspect the PG or visualise it.

This should be documented (handbook?).

@mballhausen This might be interesting for you?

````
helper.setConfigurator(new Configurator(){
        @Override
        public void inspectPG(PrecedenceInputGraph pg) {
        	helper.savePrecedenceGraph(pg, "instances/fwd.pg.xmi"); 
        }
});
````

**Comment by anthonyanjorin** [comment]
PG/protocol visualisation now works as well so this should also be documented

**Comment by erhanleblebici** [comment]
I do not really understand why do we have configurator if the helper already provides the method. The code proposed above doesn't compile as the helper is not in the scope of the configurator.

My suggestion is that the developer of this feature (anthonyanjorin) should document how he got it to work in his testing examples. 

And this feature seems to be too advanced for the handbook. If you agree on that you might close the issue by writing some javadoc to the method.

**Comment by anthonyanjorin** [comment]
I have simplified it to work now as follows:

````
helper.setConfigurator(new PGSavingConfigurator(helper, "instances/fwd.pg.xmi"));
````

**Comment by RolandKluge** [comment]
Is this issue still active?

**Comment by RolandKluge** [comment]
This issue was moved to eMoflon/emoflon-tool#20
