### ISSUE TITLE
[EA] Use a darker green for added elements

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#507]
Either hard-code this or allow to set the color via the control panel, which would be even more convenient.

**Comment by erhanleblebici** [comment]
I don't think that we should make this configurable vai control panels but set a more convenient default color by default.

**Comment by RolandKluge** [comment]
Is this already solved?

**Comment by erhanleblebici** [comment]
we are missing an EA expert for this (MDE workflow, UML Profile etc.). We have to accept the current colors.
