### ISSUE TITLE
eMoflon Build doesn't show errors

### ISSUE THREAD

**Issue by mabilov** [eMoflon/emoflon#523]
If there is a problem in TGG rules eMoflon code generation just interrupts without providing any error messages. So it is impossible to find out what is gone wrong during code generation procedure.

**Comment by anthonyanjorin** [comment]
Could you give provide us with a minimal example?  There are many types of "problems"...

**Comment by anthonyanjorin** [comment]
Please feel free to reopen this issue as soon as you can provide a concrete example.  I'm unable to reproduce it.
