### ISSUE TITLE
[EA] EA shows object variables double

### ISSUE THREAD

**Issue by SchroedingersCatIsUndead** [eMoflon/emoflon#536]
![eaproblem](https://cloud.githubusercontent.com/assets/9741282/8984529/68144882-36d2-11e5-9803-bf248050ca09.jpg)

**Comment by RolandKluge** [comment]
@jbuerdek It may help to have the corresponding EAP file.

**Comment by RolandKluge** [comment]
The bug should be fixed in the upcoming eMoflon 2.10.0. BUT: I could reproduce it due to the missing EAP file.

Please check if your problem persists and re-open the issue if necessary.
