### ISSUE TITLE
Get rid of sys out messages

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#541]
There is a continuous stream of sysout messages of which I could not yet find the origin.

Messages look like this:
Start reordering
End reordering. Went from 12 to 12 nodes, gain = 0% (1.43895373E9 sec)
<0:0><0:1, 1:0>
Garbage collection #1: 1009 nodes / 997 free / 0.0s / 0.0s total

I suspect that this has something to do with BDDs.

Can you verify this and block messages to sysout by this component?

**Comment by RolandKluge** [comment]
Seems to be gone now

**Comment by RolandKluge** [comment]
This is actually still present

**Comment by anthonyanjorin** [comment]
So it has something to do with the search plan generator and the BDD library.

Any ideas how to shut this off @fdeckwerth @gervarro?

**Comment by fdeckwerth** [comment]
I tried it years ago, but I was not successful.

The messages came somewhere from the BBD library.

**Comment by RolandKluge** [comment]
If you tell me, where the BDD library is invoked, we could mute System.out and System.err before and unmute them afterwards.

**Comment by anthonyanjorin** [comment]
I'll give that a try

**Comment by RolandKluge** [comment]
Thanks!

**Comment by anthonyanjorin** [comment]
As far as I can test (handbook examples are failing right now due to usage of story pattern names for pattern matching methods), this should be fixed now.
