### ISSUE TITLE
[EA] Tab order in OV dialog

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#544]
The tab order of the tab 'Attribute Constraint' in the OV dialog is currently non-intuitive.

After selecting the 'Attribute', pressing tab brings me to the 'Add' button instead of the 'Operator' radio button group.

**Comment by RolandKluge** [comment]
By the way, 
(i) the other tabs could also be checked
(ii) the sort order of candidates could be at least alphabetical (and later: according to the most probably matching type)

**Comment by RolandKluge** [comment]
The same goes for the "Stop Node Expression" dialog.

**Comment by RolandKluge** [comment]
For some reason, the configured TabOrder indices (OVConstraintControl, ExpressionControl, etc) are not respected.

**Comment by erhanleblebici** [comment]
first experiments with this have shown that it is "dangerous" with our EA Add-In. we should keep the add-in as stable as possible
