### ISSUE TITLE
[Handbook] Adjust section on how to get our demo and handbook examples running

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#548]
As we now want to consolidate all our workspaces and examples, our demo workspace and handbook examples are no longer zipped and supplied with the plugin but are standard workspaces just like any other.

This must be adjusted in the handbook!

**Comment by anthonyanjorin** [comment]
@RolandKluge

**Comment by RolandKluge** [comment]
This issue was moved to eMoflon/emoflon-tool#23
