### ISSUE TITLE
Remove textual sections of handbook

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#558]
As we shall take some time to restructure MOSL (probably base it on Xtext and first of all only for TGGs) for the future, we should remove the MOSL (textual) sections in our handbook.

This also involves re-writing some sentences that refer to the textual syntax and promise it.

Before starting with this task please make a tag of the handbook as "beforeRemovingTextualSections" or similar.

FYI:  @RolandKluge @SchroedingersCatIsUndead @erhanleblebici

**Comment by LarsK01** [comment]
MOSL should now be removed from the Handbook. A tag before is also created.
