### ISSUE TITLE
Build/build dirty actions don't work for working sets

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#559]
Would be nice to be able to choose multiple working sets in our dev workspace and build/build dirty all the projects in them.  Currently the build action is disabled for working sets.

FYI: @RolandKluge @erhanleblebici

**Comment by anthonyanjorin** [comment]
Export (EAP files) doesn't work either for a selection of working sets

**Comment by anthonyanjorin** [comment]
Not having this feature is like really a pain in the ass for me! :)

**Comment by RolandKluge** [comment]
Done for build, export and validate. Will appear in eMoflon 2.7.0.
