### ISSUE TITLE
[Handbook] Update handbook on new visualisation with PlantUML

### ISSUE THREAD

**Issue by Arikae** [eMoflon/emoflon#560]
Explain how the filtering with regular expressions for SDM visualization works + implement help button

**Comment by anthonyanjorin** [comment]
I would wait a bit with this - I'm working on changing the visualisation completely so any documentation would quickly be obsolete.  I'll update this issue as soon as the new vis is rolled out.

**Comment by anthonyanjorin** [comment]
Have now updated the title of this issue.

**Comment by RolandKluge** [comment]
Should be solved, right?
