### ISSUE TITLE
New release procedure

### ISSUE THREAD

**Issue by SvenPeldszus** [eMoflon/emoflon#561]
In the last releases always some major bugs were fixed and in the same release new major bugs have been included. Currently even releases on the beta site contain too much changes. Additionally the releases on the stable site do not seem to differ from the ones on the beta site except that there are fewer releases.

Please develop a new release procedure. In my opinion this release procedure should contain:

1. Much more releases on the beta site (In the best case for each changed feature one release, to avoid fixing a major bug and integration some new one in the same release)
2. The possibility to choose between the last 10 beta releases (If a beta release is buggy we can go back to a running version (currently not possible as all past beta and stable releases are buggy))
3. A stable release should always be a beta version which has been proven to be stable (only bug fixes are allowed, but no new features)
4. It should be a good idea to use branches during development
 - a) At least one stable, beta and development branch
 - b) In the best case additionally to a) one branch for each developer or new feature
5. Provide patches (svn) for bug fixes to allow developers an easy migration of bug fixes to their workspaces (if everyone has its own branch this is not necessary as bug fixes can be migrated from the stable or beta branch)

**Comment by RolandKluge** [comment]
We are currently trying to professionalize our release procedure and to integrate your feedback in these efforts.
