### ISSUE TITLE
Rethink and update usage of ANTLR, StringTemplate, TreeGrammars in light of Xtext, Xtend (and templates with Xtend)

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#567]
I think Xtext is now really stable and mature enough to be regarded as an established EMF technology.
I propose we rewrite and greatly simplify the chapter on TGGs with ANTLR+StringTemplate to use Xtext.

@erhanleblebici

**Comment by anthonyanjorin** [comment]
Have to think about how using Xtext/Xtend with its support for templates affects our current direct usage of ANTLR etc.

**Comment by RolandKluge** [comment]
This issue was moved to eMoflon/emoflon-tool#25
