### ISSUE TITLE
TGG csp constraint imports are wrong

### ISSUE THREAD

**Issue by SvenPeldszus** [eMoflon/emoflon#569]
In new csp constraints there are still used the old namespaces in the Java import declarations.

Currently in a new csp constraints the generated imports are:

```
import TGGLanguage.csp.Variable;
import TGGLanguage.csp.impl.TGGConstraintImpl;
```

The imports have to be:

```
import org.moflon.tgg.language.csp.Variable;
import org.moflon.tgg.language.csp.impl.TGGConstraintImpl;
```

**Comment by anthonyanjorin** [comment]
Done and thanks!
