### ISSUE TITLE
The final handbook solution contains some errors

### ISSUE THREAD

**Issue by LarsK01** [eMoflon/emoflon#576]
- DictionaryCodeAdapterTrafo.java has to be changed like in the handbook Part 5 fig. 2.5

- in instances the bwd.src.xmi does not work with the trafo mentioned above

**Comment by RolandKluge** [comment]
Please try to do this (You should have write access to the emoflon-tests repository - otherwise, please tell me.)

Do not hesitate to post a comment in case of problems.

**Comment by LarsK01** [comment]
Done
