### ISSUE TITLE
Add example files to the Handbook Example (4, 5) Workspace for the text-to-tree trafo

### ISSUE THREAD

**Issue by LarsK01** [eMoflon/emoflon#577]
Add the example files (numbers in english and french) also to the Handbook Example (4, 5). Until now they only exist in the final solution.

**Comment by RolandKluge** [comment]
Please place a hyperlink to the following archive in the handbook:
https://github.com/eMoflon/emoflon/raw/master/handbookfiles/chapter05/myLibrary.zip

**Comment by LarsK01** [comment]
Done
