### ISSUE TITLE
[EA] Order suggested Parameter-/ObjectVariable-/... variables by type and by prefix

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#585]
Currently, (e.g.) the suggested paramters for a StatementExpression are listed without recognizable order, also including duplicates.

Therefore, we should
(i) sort the parameters so that parameters with a "probably suitable" type are listed first
(ii) sort these parameters (and the rest) alphabetically
(iii) avoid duplicates in the list

**Comment by SchroedingersCatIsUndead** [comment]
won't fix
