### ISSUE TITLE
[EA] Addin window too large

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#586]
Currently, the EA addin window contains a "white bar" at the bottom. This causes the validation results table to become hardly legible (see below).

![validation_results_table_compressed](https://cloud.githubusercontent.com/assets/4731838/10246918/6f26ccec-6915-11e5-89e1-6129b0edeea4.png)

**Comment by SvenPeldszus** [comment]
Is it possible to change the layout of the buttons in this window?

I've always unused space in the width but I'm limited in the height. If the Buttons for "Export" and "Validate" are aligned horizontally we would save one button height.

![reorderbuttonsinea](https://cloud.githubusercontent.com/assets/2663702/10907129/cb2adfb2-8227-11e5-8f97-01827a82e802.jpg)

**Comment by RolandKluge** [comment]
Done now. For some strange reason, fixing the layout of the buttons was the only way to resize the error tablet...
