### ISSUE TITLE
All generated files in /src should be in a new /src-gen source folder

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#590]
Currently the "stubs" we generate to ease the usage of TGGs are placed in /src
The normal Eclipse convention is to place such files in a source folder named /src-gen

**Comment by anthonyanjorin** [comment]
@erhanleblebici  Please assign to who ever makes sense at the moment (Hiwi). Task is not hard but all tests should be run and the handbook adjusted (or issues should be created for this).

**Comment by RolandKluge** [comment]
This issue was moved to eMoflon/emoflon-tool#27
