### ISSUE TITLE
[EA] Attribute Constraints Dialog should be structured

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#591]
The dialog for specifying "CSP instances" should be structured in order to allow to keep EA entities (e.g. classes, attributes, variable names) consistent with the CSP specification.

The current textual syntax may become problematic if e.g. any entity changes its name.

This task could be accomplished very well by @SchroedingersCatIsUndead , I guess.
What do you think, @fdeckwerth ?

**Comment by fdeckwerth** [comment]
I agree with you, I also have some concepts (or dreams) in mind how it sould actually look.
The best might be if we make an appointment with Sascha.

**Comment by RolandKluge** [comment]
I leave this issue open as a reminder. :-)

**Comment by SchroedingersCatIsUndead** [comment]
RK: won't fix
