### ISSUE TITLE
[Handbook] Add link to eMoflon FAQs to Part 1

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#599]
We should point people to the resources in the Github Wiki during the 'Installation' part of the Handbook:

https://github.com/eMoflon/emoflon/wiki/FAQs

Additionally, we should explicitly mention, where to find help if EA does not load the eMoflon addin: 

https://github.com/eMoflon/emoflon/wiki/Using-EA-With-A-Second-Windows-Account

**Comment by LarsK01** [comment]
Done
