### ISSUE TITLE
[TGG] Progressmonitor for TGG execution

### ISSUE THREAD

**Issue by SvenPeldszus** [eMoflon/emoflon#604]
It would be nice to have the ability to handover an ```IProgressMonitor``` to the TGG execution for an estimation how much of the work is done. 

The monitor could e.g.  go one step forward for each processed match.

**Comment by RolandKluge** [comment]
Good idea! I guess a general solution could be to provide 'hooks' in the TGG algorithm, where you may register listeners that could also handle cancelation (This issue would then be quite similar to #600).

**Comment by RolandKluge** [comment]
This issue was moved to eMoflon/emoflon-tool#29
