### ISSUE TITLE
Support EList Attributes

### ISSUE THREAD

**Issue by SvenPeldszus** [eMoflon/emoflon#606]
In the GRaViTY project we have some information stored in attributed of the type ```EList```. Currently a native handling of such attributes is not possible.

E.g. the package of a class is stored in such an ```EList```. For the Java class ```a.b.c.Example``` an according node in a graph representation has an attribute of the type ```EList``` with the following contents: ```["a", "b", "c"]```. Currently it is not possible to acces such information in eMoflon. Currently we have to convert such ```ELists``` into an object based format to access this information. Therefore we modelled in our source and target model a double linked list and convert the ```EList``` into this representation in a preprocessing. 

![paramlist](https://cloud.githubusercontent.com/assets/2663702/10908029/de23def0-822e-11e5-8df3-4858c5bb5f21.jpeg)

Our double linked list consists out of an ```EClass``` representing this List (```TParameterList```). This ```EClass``` aggregates multiple entries (```TParameter```) and has a reference to the first entry of the list. Each of the entries has a reference to the previous and next entry.

However, it would be be beneficial, if attributes of the type ```EList``` are supported by eMoflon and we can get rid of this preprocessing. In general this could include to allow data types in SDM story nodes and TGGs. In this case ```data types``` could be a new node type in this diagrams and are connected over some ```attribute``` edge with the ```object variables```.

**Comment by SchroedingersCatIsUndead** [comment]
sry not enough man power.
Cool thing but we can't provide it.
