### ISSUE TITLE
Fix errors in our generated SDMs

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#612]
In our current demo workspace, Xtext is performing some kind of simple validation of ecore models and shows that our generated SDMs are a bit problematic.

For example the comments feature is required but is not set by our compiler.  These problems are a bit disturbing and we should eventually decide what to do:

* Fix the SDM metamodel
* Fix our compiler to really set all these required attributes
* Programmatically remove all Xtext Check problem markers on our derived artefacts

**Comment by RolandKluge** [comment]
Personally, I suggest to set the comment and name(?) fields to a sensible default value.

**Comment by anthonyanjorin** [comment]
Just found out that Xtext also complains about "foreign" metamodels as it cannot automatically resolve the URIs (we use extra settings in our property file to do this).

I'm now wondering if the best solution would just be to automatically remove all problem markers of type "Xtext Check (fast)".

**Comment by anthonyanjorin** [comment]
Now fixed for my example.  We can extend this marker removal as necessary in the future.

**Comment by anthonyanjorin** [comment]
I have to check the entire project for these damned markers.  EMF sometimes copied fragments of the metamodel all about (I guess for efficiency reasons).
