### ISSUE TITLE
__ignore__ dependencies in MOCA tree

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#620]
The exported MOCA tree of org.moflon.sdm.compiler.democles.specification contains several dependencies that are named __ignore__. While this seems to be no major problem, it would be interesting to find out why these spurious dependencies are being added.

@anthonyanjorin Do you have an idea?

**Comment by anthonyanjorin** [comment]
If I remember correctly, the EA addin checks if dependencies are also exported.  If they are then they are in the target workspace as actual projects and are handled accordingly (searched for, opened if closed, etc).

If they are not exported, then they are NOT in the workspace, meaning they are either installed plugins or are jar files etc.  In this case they still need to be handled as dependencies (so cannot be completely omitted I think), but we need to know not to complain, e.g., if the projects are missing.

It must be something along these lines - I would have to check the C# code and Eclipse plugin for more details on how the entries are created and used.

**Comment by RolandKluge** [comment]
OK, then I guess this is not a bug but rather a feature. :-)

**Comment by anthonyanjorin** [comment]
Well, yes...  but probably more an EA hack :(
