### ISSUE TITLE
[EA] Import .ecore files with sevral root packages

### ISSUE THREAD

**Issue by erhanleblebici** [eMoflon/emoflon#621]
Altough we never do that in eMoflon, .ecore files might have several root packages. A lot of examples for this can be found in this metamodel zoo: http://www.emn.fr/z-info/atlanmod/index.php/Ecore 

In this case, each root package must be imported as an own metamodel but the references between the classes of these metamodels must be imported as well.

Lets take this .ecore file as example: http://gforge.inria.fr/scm/viewvc.php/atlantic-zoos/AtlantEcore/LaTeX.ecore?view=co

There are two root packages: LaTeX and PrimitiveTypes. The EA import should expectedly create the two metamodels LaTeX and PrimitiveTypes. Note that some EClasses in LaTeX-package are referencing some EDataTypes in PrimitiveTypes-package.

**Comment by SchroedingersCatIsUndead** [comment]
implemented
