### ISSUE TITLE
Find solution for conflict with eMoflon's ANTLR version

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#624]
Xtext uses a patch for an old version of ANTLR and this is in conflict with our own ANTLR plugin/jar.

This is the reason why the generated Xtext lexer and parser contain compilation errors if you try to build the Xtext grammar in our dev workspace.  Working in a new workspace only containing MOSL solves the problem.  Would be nice to find out how to resolve this conflict.

**Comment by anthonyanjorin** [comment]
I'm avoiding this right now by just using a separate workspace for working on MOSL.  I can live quite well with this solution.

**Comment by gervarro** [comment]
I think that this issue might be resolved by appropriately configured manifest.mf files.
