### ISSUE TITLE
[TGG MOSL] avoid lexer clashes between our keywords and user specification

### ISSUE THREAD

**Issue by erhanleblebici** [eMoflon/emoflon#626]
![screenshot 2015-12-15 16 16 46](https://cloud.githubusercontent.com/assets/11506522/11814543/a0d2072c-a347-11e5-9384-a29f05ca71cb.png)

You see in the screenshot a very strange Xtext error for the "sons" reference. The lookahead mechanism of Xtext believes the user wants to write "src" and not "sons". It suggests therefore that 'o' should be replaced by 'r'.

In order to avoid such clashes, please add a @ prefix for our keywords src and trg in the grammar.
Example:

correspondence {
	++  fooToBar : FooToBar {
		-@src->foo
		-@trg->bar
	}
} 

The same prefix won't be used for other types of edges, such that Xtext can easily distinguish between our keywords and user specification.

**Comment by anthonyanjorin** [comment]
we could keep to this convention as much as possible (adding @ to keywords so they do not clash with reference names etc)
