### ISSUE TITLE
[TGG MOSL] Xtext to TGG does not work if src/org/moflon/tgg/mosl/rules does not exist

### ISSUE THREAD

**Issue by erhanleblebici** [eMoflon/emoflon#627]
The forward transformation (from Xtext model to internal TGG model) throws exception if the folder src/org/moflon/tgg/mosl/rules does not exist. In order to handle Xtext-TGG specifications where everything is specified in Schema.tgg, the forward transformation must be made robust such that it is fine to have no rules folder.

**Comment by anthonyanjorin** [comment]
This is actually related to #616
