### ISSUE TITLE
Code Review for MOSL

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#631]
* Post-processing should be refactored into multiple small methods (right now it is one big fat scary method).
* Separate classes should be used for pre and post-processing.  Right now they are both in the generated Trafo class, which is not such a good idea.
* Any commented out lines should be deleted.

**Comment by anthonyanjorin** [comment]
General improvements for code quality and readability etc.

**Comment by anthonyanjorin** [comment]
This should best be done once all our TGG-based tests are running with MOSL @erhanleblebici

**Comment by RolandKluge** [comment]
This issue was moved to eMoflon/emoflon-tool#31
