### ISSUE TITLE
Clean up synchroniser 

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#632]
Due to future plans for the interpreter we can now clean up our synchroniser and remove obsolete annotations etc made for the debugger.

**Comment by anthonyanjorin** [comment]
I've already done some work on this.  If you could take a brief look over then we could close this issue.

**Comment by erhanleblebici** [comment]
debugger is completely removed from eMoflon. Synchronizer is currently in a good form, and probably there will be a new one when we use interpreter.
