### ISSUE TITLE
Extend TGG visualisation to somehow show amalgamation

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#633]
As amalgamation is not flattened in any way, we must think of a way of visualising amalgamating rules in dot.

**Comment by anthonyanjorin** [comment]
What is missing right now is an additional visualisation TGG for rules and their relations (refinement, amalgamation).  Currently we only have a visualisation of TGG Rules (as patterns).

**Comment by RolandKluge** [comment]
This issue was moved to eMoflon/emoflon-tool#32
