### ISSUE TITLE
Many new "build.xml" and "javaCompiler...args" files

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#637]
When building the dev workspace with eMoflon 2.8.0, a number of projects contain "build.xml" and "javaCompiler...args" afterwards.

@gervarro @anthonyanjorin Any idea?

**Comment by gervarro** [comment]
@RolandKluge: Did you install a new Eclipse?
Anyway, in such a case, I typically prepare two instances of dev. workspaces, and I start the second instance from the first in debug mode to be able to check in details what is going on.

**Comment by RolandKluge** [comment]
OK, then I will try the usual process. I thought, this may be some desired behavior introduced by some of the recent changes.

**Comment by RolandKluge** [comment]
Closing this issue since this problem only seems to affect me.
