### ISSUE TITLE
Add demo workspace to other examples on github?

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#639]
Our demo workspace is still in our SVN repo right?  If I understand correctly this means that users cannot check out the workspace when working through our handbook (right at the start actually).

Another argument for moving the examples to github is that one doesn't need to install anything at all to try it out (git support is provided by default).

**Comment by RolandKluge** [comment]
Done.

**Comment by RolandKluge** [comment]
Can be found here: https://github.com/eMoflon/emoflon-examples/tree/master/demo
