### ISSUE TITLE
Handbook examples (TGGs) are not compiling due to names of pattern matching methods

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#640]
Pattern matching methods have been recently adjusted to using names from the corresponding story nodes.  This has apparently not been tested extensively enough.

At least the handbook TGGs do not compile any longer.  Please run all our tests to ensure that the implemented strategy is robust enough.

**Comment by anthonyanjorin** [comment]
If I am not mistaken, this does not seem to be tested at all, Test Misc does not compile (even "normal" SDMs).

**Comment by anthonyanjorin** [comment]
Just checked, I am up-to-date.

**Comment by RolandKluge** [comment]
Sorry for the inconvenience. In fact, it was just one character that caused the bug: Whitespaces were replaced with '-' instead of '_' (the first one is not allowed to appear inside Java identifiers).

**Comment by RolandKluge** [comment]
All tests green again
