### ISSUE TITLE
Check in current version of eMoflon logo

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#641]
Could you check in the current files of the eMoflon logo into the SVN?

What about here: org.moflon.doc.workspace.configuration/logo ?

**Comment by RolandKluge** [comment]
Desired formats:
 - PDF
 - PNG
 - SVG (I will try out whether I can also open/edit the SVGs using Inkscape)

**Comment by anthonyanjorin** [comment]
Done.  The SVG doesn't look so good (font is supposed to be monospaced but looks weird in Internet Explorer).  The logo can be redrawn pretty easily, just look for Aries (Unicode) and place eMoflon written in a monospaced font below.
