### ISSUE TITLE
ecore importer: create Ecore Diagram instead of Class Diagram

### ISSUE THREAD

**Issue by LarsK01** [eMoflon/emoflon#643]
When importing a ecore file a Class Diagram will be automatically created. But for the validation a Ecore Diagram is needed.
So create an Ecore Diagram instead of a Class Diagram

![fehler](https://cloud.githubusercontent.com/assets/12693338/12166184/56a70d98-b524-11e5-98e0-4543fc1dcce5.jpg)

**Comment by SchroedingersCatIsUndead** [comment]
solution found and problem fixed
