### ISSUE TITLE
ecore importer: literls of enumeration does not work

### ISSUE THREAD

**Issue by LarsK01** [eMoflon/emoflon#644]
After import, the literals of enumerations is missing.
Example ecore model:

[exampleFile.zip](https://github.com/eMoflon/emoflon/files/81340/exampleFile.zip)

**Comment by SchroedingersCatIsUndead** [comment]
I cannot reproduce the bug with the example File 


![examplefileimport](https://cloud.githubusercontent.com/assets/9741282/12352499/ccad1074-bb86-11e5-80b9-4f52d9775870.PNG)

**Comment by SchroedingersCatIsUndead** [comment]
already fixed
