### ISSUE TITLE
ecore importer: Selecting eap-file works only if project name is equal.

### ISSUE THREAD

**Issue by LarsK01** [eMoflon/emoflon#646]
When selecting a eap-file the importer searches for a eap file with the name of the project, which contains the eap-file.

For Example: 
Projectname: TestProject
Eap name in the project: fiel.eap

When selecting file.eap for the export, a error occurs that TestProject.eap could not be found. Although selecting the eap, the importer tries to resolve the name by the project-name.

**Comment by RolandKluge** [comment]
@SchroedingersCatIsUndead  Personally, I think that we should decouple the import process from our 'project name = EAP file name' convention. We do not lose anything and it is much easier to work with the importer if we do not have to consider this restriction.

**Comment by SchroedingersCatIsUndead** [comment]
fixed
