### ISSUE TITLE
ecore importer: refresh MocaTree after whole import

### ISSUE THREAD

**Issue by LarsK01** [eMoflon/emoflon#647]
After import of the example file (see appendix) the role names of the associations are missing. After refreshing the MocaTree (by adding all Elements to an Ecore Diagram and double click on them and close the window with OK or deleting the memo Moflon::ChangesTree and clicking again on the element) the role names are correct. So make an automatic refresh after the whole import.
The role names are in EA but in the MocaTree they are missing without the refresh.

[ExampleFile.zip](https://github.com/eMoflon/emoflon/files/82258/ExampleFile.zip)

**Comment by LarsK01** [comment]
This problem occurs not only at associations. Also at EEnums it occurs. After double clicking on the element in the diagram and pressing then OK solves the problem too. The literals in the MocaTree are also double, whereat one has an value at the field "value" and the other hasn't it.

For you DummyTest ecore model you get the following memo file for the MocaTree:

"<MocaTree:Node xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:MocaTree="platform:/plugin/MocaTree/model/MocaTree.ecore">
  <children name="EEnum" index="0" xsi:type="MocaTree:Node">
    <children name="literals" index="0" xsi:type="MocaTree:Node">
      <children name="EEnumLiteral" index="0" xsi:type="MocaTree:Node">
        <attribute name="name" value="ONE" index="0" />
        <attribute name="value" value="" index="1" />
        <attribute name="literal" value="ONE" index="2" />
      </children>
      <children name="EEnumLiteral" index="1" xsi:type="MocaTree:Node">
        <attribute name="name" value="TWO" index="0" />
        <attribute name="value" value="" index="1" />
        <attribute name="literal" value="TWO" index="2" />
      </children>
      <children name="EEnumLiteral" index="2" xsi:type="MocaTree:Node">
        <attribute name="name" value="THREE" index="0" />
        <attribute name="value" value="" index="1" />
        <attribute name="literal" value="THREE" index="2" />
      </children>
      <children name="EEnumLiteral" index="3" xsi:type="MocaTree:Node">
        <attribute name="name" value="ONE" index="0" />
        <attribute name="value" value="0" index="1" />
        <attribute name="literal" value="ONE" index="2" />
      </children>
      <children name="EEnumLiteral" index="4" xsi:type="MocaTree:Node">
        <attribute name="name" value="TWO" index="0" />
        <attribute name="value" value="1" index="1" />
        <attribute name="literal" value="TWO" index="2" />
      </children>
      <children name="EEnumLiteral" index="5" xsi:type="MocaTree:Node">
        <attribute name="name" value="THREE" index="0" />
        <attribute name="value" value="2" index="1" />
        <attribute name="literal" value="THREE" index="2" />
      </children>
    </children>
    <attribute name="name" value="EnumerationInModel" index="0" />
    <attribute name="guid" value="{DED8CCBC-B1F7-0000-0000-000000000020}" index="1" />
  </children>
</MocaTree:Node>"

**Comment by SchroedingersCatIsUndead** [comment]
fixed
