### ISSUE TITLE
Open PSF selection dialog does not work

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#648]
The PSF selection dialog is really cool but it is buggy:  The workspace relative path is appended to C: instead of to the location of the workspace.

@RolandKluge

**Comment by anthonyanjorin** [comment]
If Load custom PSF or PSF selection dialogue is chosen but then cancelled, a cryptic error message is shown.  This could be more elegant (robust).

**Comment by RolandKluge** [comment]
I fixed this issue for the 'Load custom PSF' dialog.
However, I could not reproduce the bug for the 'PSF selection dialog' - nothing happens if I press Cancel.

**Comment by RolandKluge** [comment]
@anthonyanjorin 
> 'The workspace relative path is appended to C: instead of two the location of the workspace.'
Do you mean the 'PSF selection' dialog oder the 'Load custom PSF' dialog? 
Can you give more details: Which PSF did you select?

**Comment by anthonyanjorin** [comment]
Choose 'Open PSF selection dialog' and select 'dev\TGG_Modules.psf'
Instead of starting the process, nothing happens.

**Comment by RolandKluge** [comment]
OK, the problem was that I used IFile#getFullPath instead of IFile#getLocation. Now, the problem is fixed - tried it with the TGG module without problems
