### ISSUE TITLE
Problems when deleting org.moflon.tgg.language

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#651]
When I want to erase the project org.moflon.tgg.language from the workspace (I tick the 'Remove from file system' checkbox as well), the following error appears and the project cannot be deleted:

Could not delete '/org.moflon.tgg.language/lib'.

Could it be that these libraries are somehow 'locked'?

**Comment by erhanleblebici** [comment]
we don't have any special locks in the tgg.language project. This seems to be a bug deep in Eclipse File management (checked the stack trace). Manual deletion (simply a second try) is the most common solution you can find in the forums. I close the issue as I don't think that we should further investigate this.
