### ISSUE TITLE
Integrate MOSL projects into TGG module?

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#654]
I guess this would make sense right?  It might be a bit challenging as we would have to invoke the MWE workflow file as part of our automated build process.  I'm pretty sure this is possible though.

Or do you prefer an extra MOSL workspace?  I don't really care.

We should also create an optional feature just like for our visualization modules.

**Comment by erhanleblebici** [comment]
done (by Roland)
