### ISSUE TITLE
Minimal example for which backward trafo does not work

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#657]
[test.zip](https://github.com/eMoflon/emoflon/files/119800/test.zip)

FYI:  @erhanleblebici

**Comment by anthonyanjorin** [comment]
@erhanleblebici : As discussed, of this is because of an initially missing attribute condition library, then the action could first make sure this file exists.

**Comment by thomaskovac** [comment]
The BackwardPostProcess didn't generate the correct import Strings, its fixed now.
