### ISSUE TITLE
Visualization freezes Eclipse when it takes a bit longer

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#658]
Would be nice to have the visualization running as a separate job in its own thread so it doesn't block the Eclipse UI.

@RolandKluge :  You know how to do this right?  Could you fix this or tell me how to?

**Comment by RolandKluge** [comment]
As far as I can see, the relevant piece of code is the invocation of org.moflon.ide.visualisation.dot.language.EMoflonDiagramTextProvider.getDiagramText(IEditorPart, ISelection)

This invocation appears to be synchronous, so refactoring the translating TGG into a job makes no sense.

Still, the drawing of an Ecore diagram (net.sourceforge.plantuml.ecore.EcoreDiagramTextProvider ?) does not block the UI thread. Strange.

**Comment by anthonyanjorin** [comment]
Why does the invocation have to be synchronous? Isn't that the problem?

**Comment by RolandKluge** [comment]
Even when outsourcing the code to a separate Job, the invoking method (i.e., getDiagramText) would have to wait for the Job to finish and nothing would be gained, I guess. Or am I mistaken here?

**Comment by anthonyanjorin** [comment]
Ok - if I understand correctly, you mean that we have no control over how the method "getDiagramText" is invoked by PlantUML.  If it is not an asynchronous job then there's nothing we can do to change that.

What do you mean by:  

> Still, the drawing of an Ecore diagram (net.sourceforge.plantuml.ecore.EcoreDiagramTextProvider ?) does not block the UI thread. Strange.

?

**Comment by RolandKluge** [comment]
> you mean that we have no control over how the method "getDiagramText" is invoked by PlantUML.
This is my impression, yes. 

> What do you mean by: 
I tried to analzye the source code for the Ecore-visualizing counterpart, but it seems to be a synchronous invocation as well - no job, nothing special in the *plugin.xml*. However, this procedure does not seem to block the UI, as far as I could test it. Disclaimer: I am not 100% sure that I analyzed the source code that matches the version of the Eclipse plugin.

**Comment by anthonyanjorin** [comment]
ok - this problem might just go away (at least for reasonably sized diagrams) once we reduce the ridiculous amount of code we generate (which is causing the awful lag the first time you run the transformation due to class loading).

what do you think of having a timeout?  Maybe we should refactor our TGG algorithm to use a progress monitor and react to CANCEL...

**Comment by RolandKluge** [comment]
> Maybe we should refactor our TGG algorithm to use a progress monitor and react to CANCEL...

This is something that was also already requested by Sven (#604). However, in this context, no progress monitor is passed as parameter, so it is not possible to interrupt the processing.

**Comment by anthonyanjorin** [comment]
This might turn out to be an argument for implementing our own (SVG) view one day.
