### ISSUE TITLE
Validation rule for MOSL:  no ++ for abstract types

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#661]
We should ensure that ++ is not used for abstract types as this does not makes sense (generated code will not compile).

An exception is if the rule is an abstract refinement rule.

FYI:  @erhanleblebici @thomaskovac

**Comment by SchroedingersCatIsUndead** [comment]
error created.
I also created a quick fix wich change the Rule to an abstract Rule.
