### ISSUE TITLE
Validation rule:  OV names must be unique

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#666]
This should be flagged as an error, maybe with a quickfix to add a "2" as prefix?

FYI: @erhanleblebici  @thomaskovac

**Comment by SchroedingersCatIsUndead** [comment]
added error flag

**Comment by SchroedingersCatIsUndead** [comment]
created & committed

**Comment by SchroedingersCatIsUndead** [comment]
I have added a Solution and tested it. I have worked about 20 hours with it. I have not get any unexpected error like reclaiming a name exists although it does not exist.
