### ISSUE TITLE
Errors in validation are not reported properly

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#668]
In org.moflon.compiler.sdm.democles.eclipse.DemoclesValidatorTask.validateEClass(EClass, MultiStatus, IProgressMonitor), the resulting 'cancelStatus' may contain errors that occurred during the validation. There should be a check whether the status is Status.ERROR and a multi-status should be created and propagated if necessary.

FYI @gervarro

**Comment by RolandKluge** [comment]
@gervarro I am a little unsure how to solve this. RuntimeExceptions are caught on the level of EOperation validation and on the level of EClass validation. Would it make more sense to only catch them on one level?

**Comment by gervarro** [comment]
I do not really understand what the problem/bug is. If the user explicitly pressed cancel during the validation (the only situation resulting in a Status.CANCEL), then no errors should be reported.

As far as I know, the original validation task (before commit 517) included one single run method with the appropriate handling of RuntimeExceptions. A RuntimeException means an internal error in the validation process, and in this sense it does not really matter whether it appears on the EOperation or on the EClass level (which distinction did not exist at all in the original process). Are there any situations, in which a RuntimeException is really thrown, and it is not a bug in the validation?

**Comment by RolandKluge** [comment]
The problem was that the validation crashed on the EOperation level, causing a RuntimeException, that was caught and wrapped in an appropriate ERROR-Status object. However, this status was ignored because the surrounding code only checks for CANCEL.

The easiest solution is to remove the inner try-catch. In this case the first RuntimeException will cause the validation to stop. Currently, the results are collected in a MultiStatus, which is then reported as 'regular' problem as Marker on the Ecore file. This error message is, however, not very telling.

**Comment by gervarro** [comment]
> The easiest solution is to remove the inner try-catch. In this case the first RuntimeException will cause the validation to stop. Currently, the results are collected in a MultiStatus, which is then reported as 'regular' problem as Marker on the Ecore file. This error message is, however, not very telling.

In a bug free validation module, a `RuntimeException` should never be thrown. The behaviour to stop the validation in case of an internal error/bug is OK. Such internal errors should be reported to and fixed by us, as they are not specification errors. The 'report the bug' error message can obviously be improved if you do not like it, but I would never report such an internal error, in the same way as a regular specification error.

**Comment by RolandKluge** [comment]
OK, I did it this way.
