### ISSUE TITLE
Search plan generation takes forever when adding complex attribute constraints

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#671]
(you find the files in the commit cited below)

How to reproduce:
1) Just export the whole metamodel - you may have to set Export=true for de.tudarmstadt.maki.modeling.graphmodel
2) The problematic location is DistanceKTC::checkPredicate: When inserting the attribute constraint into the CSP box in story node *CheckIf_otherLink1_isTheShortest*, the search plan generation does not terminate.

**Comment by fdeckwerth** [comment]
Seems that using new attibute constraint and old attribute expressions for the same attribute does not work.

I was able to fix your spec by removing all old attrib constraint that refer to the "distance" attribute and changing CSP spec to

*(tmp:EDouble, otherLink1.distance, this.k);
>=(maxLink.distance, tmp:EDouble);
>=(maxLink.distance,otherLink2.distance);
>=(otherLink2.distance,otherLink1.distance);

**Comment by RolandKluge** [comment]
Oh cool, thank you! What about the attribute constraints relating to the "State" enum type?

**Comment by RolandKluge** [comment]
Problem solved, indeed.
