### ISSUE TITLE
Fix ComponentLanguage in Zoo1-TestSuite for new Attribute Constraints

### ISSUE THREAD

**Issue by erhanleblebici** [eMoflon/emoflon#674]
Currently ComponentLanguage in Zoo1 won't generate code as its attribute constraints are not adjusted for the new syntax (:: must be used instead of : according to Fred)

**Comment by erhanleblebici** [comment]
@RolandKluge FYI

**Comment by RolandKluge** [comment]
@fdeckwerth Is this solved, actually?

**Comment by RolandKluge** [comment]
Done because all tests are green for eMoflon 2.13.0.
