### ISSUE TITLE
ecore importer: upperbound of associations not correct

### ISSUE THREAD

**Issue by LarsK01** [eMoflon/emoflon#676]
When importing associations the upperbound is allways set to 1, also if the upperboundis larger 1 or -1.
In the EA diagram the upperbound is correct, but at the memo files of the field "Moflon::ExportTree" of the associations are incorrect.

After opening the properties of the association in an EA diagram and pressing the "OK" button the upperbound is in the memo file correct.

**Comment by SchroedingersCatIsUndead** [comment]
fixed
