### ISSUE TITLE
Fix sub-package resolution for SDM-CSPs

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#680]
// Top-level package x
    // Sub-package x.y with EEnum Foo (with constants A,B,C)
    importPackage x.y;
    =(x:Foo, A::Foo);

@fdeckwerth: How do we fix this?

**Comment by fdeckwerth** [comment]
Can be fixed by adapting method:
org.moflon.core.mocatomoflon AttributeConstraintsExporter::resolvePackageImport

**Comment by RolandKluge** [comment]
Done.
