### ISSUE TITLE
Add known issue concerning XText to FAQs

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#681]

**Comment by anthonyanjorin** [comment]
The issue here is that one must install Xtext before installing eMoflon (with MOSL).

**Comment by RolandKluge** [comment]
An item has been added to the FAQs: https://github.com/eMoflon/emoflon/wiki/FAQs

**Comment by anthonyanjorin** [comment]
A better solution would be to handle XText as a dependency such as PlantUML, which is automatically resolved when installing eMoflon.  I hope this is possible.

**Comment by anthonyanjorin** [comment]
In any case, this should be addressed in the handbook, especially if it is impossible to automatically install XText if necessary.

**Comment by RolandKluge** [comment]
I think, this should not be a problem: There are update sites for XText: https://eclipse.org/Xtext/download.html

**Comment by RolandKluge** [comment]
I added the update site as associated site and the XText feature as required feature.

Please try it out and re-open the issue if necessary.
