### ISSUE TITLE
Optimize syntax highlighting for STG files

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#687]
The simple editor with basic syntax highlighting is fine but also unfortunately very inefficient (for large STG file).

Would be great if this could be simplified or optimized so it scales.

**Comment by RolandKluge** [comment]
@anthonyanjorin  What is a sample STG file, with which I could experiment?

**Comment by anthonyanjorin** [comment]
TGGMain.stg

**Comment by RolandKluge** [comment]
I was not able to trace down the source of the inefficiency.

It seems that the most often called method is org.moflon.ide.texteditor.editors.MoflonTextEditor.getAdapter(Class)

@erhanleblebici Maybe you could have a look at this?

**Comment by RolandKluge** [comment]
This issue was moved to eMoflon/emoflon-tool#35
