### ISSUE TITLE
Add support for ENUMS in attribute conditions

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#688]
We still cannot deal well with ENUMS (in for example attribute conditions).

Is this due to Democles?  I doubt it -- probably just a remnant of EA related restrictions.  With MOSL it should now be possible to handle ENUMS just as well as anything else.

FYI:  @RolandKluge @gervarro @erhanleblebici

**Comment by gervarro** [comment]
I do not understand the situation. The complete bootstrapping process would fail, if enums were not supported. Btw. there are 2 kinds of attribute handling in eMoflon:
- The basic support for SDMs that you can configure in the graphical pop-up windows. (I would be really surprised, if this part failed. The bootstrapping process uses only this part.)
- Fred's attribute framework that can be configured via the textual DSL. I do not know what the current state of Fred's framework is.

Could you explain more precisely what is missing?

**Comment by RolandKluge** [comment]
In fact, enums are supported (since a month or so) in the EA application constraints (aka CSP constraints).
For instance:

    usingPackage Ecore;
    =(x:SomeEnum, CONSTANT::SomeEnum);

A detailed description will be added to the handbook during the next hacker days.

**Comment by anthonyanjorin** [comment]
ok that sounds promising...  I meant attribute conditions in TGG rules using the new textual syntax.

So I think all we need to do is (1) tweak the syntax to allow ENUMS (with code completion etc.), (2) adjust the mapping to cover ENUMS as required.

What I do not understand right now is if ENUMS are just Literals (according to the SDM metamodel) which are magically parsed correctly, or if there is now an ENUMExpression or similar in the metamodel.

**Comment by RolandKluge** [comment]
@fdeckwerth Can you provide details on this?
