### ISSUE TITLE
Handbook:  Discontinue documentation for Part 5

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#693]
No one currently has the time and effort to maintain our model-to-text functionality (a large part of which can and maybe even should be replaced by Xtext, Xtend, etc).

As a first step towards focussing on our core competence, I suggest we remove Part 5 of the handbook.

This means:

+ Updating the website so there are only 5 parts (Part 6 becomes Part 5) -->  Could you do this @RolandKluge ?
+ Moving the current Part 5 handbook project to our "Attic", and renaming Part 6 to Part 5 --> I've assigned this to @erhanleblebici 

I'll be updating Part 4 on TGGs.

**Comment by RolandKluge** [comment]
OK, I will comment out Part 5 during the hacker days.

**Comment by RolandKluge** [comment]
Homepage: Done
Move to attic: Done
