### ISSUE TITLE
What project is org.moflon.doc.handbook.99_gettingStarted?

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#696]
And what is the goal of this?  A mini tutorial?  I like the idea but it also means more work maintaining this in addition to our handbook (and we are already struggling here).

**Comment by RolandKluge** [comment]
This was intended as a mini tutorial. It should currentlty NOT appear in the handbook and may be removed because we decided that it is too much effort (as you already said).

@erhanleblebici Can you do that?

**Comment by RolandKluge** [comment]
While preparing the hacker days, I moved this to the attic.
