### ISSUE TITLE
Establish WorkspaceUIHelper in org.moflon.ui to get rid of UI dependencies in WorkspaceHelper

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#702]
FYI:  @gervarro @RolandKluge

**Comment by RolandKluge** [comment]
In fact, this is not so easy: The only references to "Eclipse UI" are the following:

    import org.eclipse.ui.IWorkingSet;
    import org.eclipse.ui.IWorkingSetManager;
    import org.eclipse.ui.PlatformUI;

However, these dependencies are used also (and naturally) in org.moflon.ide.core, which should actually not contain UI code.

@anthonyanjorin Should we move the eMoflon builders to the UI?

**Comment by gervarro** [comment]
No. We should try to separate the handling of working sets from the build process.
@RolandKluge Let us discuss this problem at some time face-to-face.

**Comment by RolandKluge** [comment]
OK, I created a WorkspaceHelperUI, the rest is a process rather than a single task.
