### ISSUE TITLE
Host beta and release update sites on Github?

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#704]
Would be nice to allow every developer to deploy beta and release... not only ES Mitarbeiter :)

If github can work then that would be a nice solution.

**Comment by RolandKluge** [comment]
This seems to be uncomplicated. With GitHub Pages, I was able to push the current update site here: https://emoflon.github.io/eclipse-plugin/beta/update-site2/

An option would be to host the full website on GitHub. Advantages: No more Typo3, less complicated user management,...

**Comment by RolandKluge** [comment]
Still needs to be documented on the homepage and in the Wiki.

**Comment by RolandKluge** [comment]
Documented on homepage and in handbook.
