### ISSUE TITLE
Get rid of managed EAP files

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#708]
If we want to switch to git in the long run, we should get rid of the managed EAP files.

The only affected projects are
* org.moflon.core.languages.specification
* org.moflon.tgg.specification

@anthonyanjorin @erhanleblebici  Any concerns against this plan?

**Comment by anthonyanjorin** [comment]
Well...  we could just postpone this until we have gotten rid of EA :)

**Comment by RolandKluge** [comment]
Done.
