### ISSUE TITLE
[TGGs] rename "fwd/bwd.src/trg.xmi" to "fwd/bwd.in/out.xmi" in generated helper classes

### ISSUE THREAD

**Issue by erhanleblebici** [eMoflon/emoflon#709]
the words "src" and "trg" in helper classes are being used as input or output for a transformation. this can easily be confused with src and trg in the TGG terminology. 

Handbook and handbook examples should be adjusted as well.

**Comment by RolandKluge** [comment]
This issue was moved to eMoflon/emoflon-tool#41
