### ISSUE TITLE
Visualisation:  Provide a visualisation for the entire TGG

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#710]
This would show all rules as a graph with refinement connections...

This could be shown when one chooses the root element of a tgg.xmi file.

I'm not sure when this should be shown for the TGG MOSL editor...  perhaps when for the schema/schema file?  This might be more useful than visualising the correspondence types (which are all ready pretty clear in the schema file itself right?)

**Comment by anthonyanjorin** [comment]
This is a duplicate of #689

**Comment by anthonyanjorin** [comment]
Lets trigger this when:
1. The user opens the schema file (schema.tgg), the cursor is anywhere in the file, and it does not contain any TGG rules
2. The user chooses the root of a triple graph grammar XMI file (i.e., the type Triplegraphgrammar) in the normal model editor
3. The user selects the name of the schema in a schema file (or any arbitrary .tgg file) that also contains TGG rules
4. The user is in a .tgg file with multiple TGG rules and the current selection is not a TGG rule name

I hope this is all clear.

**Comment by SchroedingersCatIsUndead** [comment]
done
