### ISSUE TITLE
Template for eMoflon URIs won't work for projects with dots

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#713]
For a project with name "org.moflon.foo" the current MOSL template for import URIs will produce:

#import "platform:/plugin/org.moflon.foo/model/org.moflon.foo.ecore

instead of:

#import "platform:/plugin/org.moflon.foo/model/Foo.ecore"

I'm not sure how this can be fixed as one would require invoking a method (lastSegment.firstToUpper).
Perhaps Xtext has a mechanism for such "intelligent" templates?

**Comment by RolandKluge** [comment]
@SchroedingersCatIsUndead Is this issue already solved?

**Comment by RolandKluge** [comment]
This issue was moved to eMoflon/emoflon-tool#43
