### ISSUE TITLE
Ugly and cryptic error for a new schema due to missing correspondence types

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#723]
The editor now complains if there is no correspondence type in a schema.

This is good but the error message is directly from the parser and is extremely cryptic.  It is also shown immediately the schema is opened, i.e., before the user has a chance to do anything at all :(

Would it be possible to improve this error message?  If this is impossible we should again remove the constraint from the parser and add it as a validation (even if this seems clunky).

**Comment by RolandKluge** [comment]
This issue was moved to eMoflon/emoflon-tool#47
