### ISSUE TITLE
Presentation of refined variables

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#726]
To indicate that a variable is being refined in a rule refinement, it would be better to use underlining or something else (perhaps bold, or very light, or ...?) that can be combined with the normal colouring (e.g., green).  Using colours (currently purple) is not so clever as this is "shadowed" if the variable is green.

Please try out what looks best and consider other things (e.g., how are NACs depicted)

**Comment by SchroedingersCatIsUndead** [comment]
done in #736
