### ISSUE TITLE
MOSL-TGG: SVN wants to remove AttrCondDefLibrary.tgg

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#728]
Whenever I build the developer workspace, SVN wants to remove AttrCondDefLibrary.tgg afterwards (shown as '-' in the Team Synchronization View).

This is annoying and pollutes the view.

@anthonyanjorin @erhanleblebici FYI

**Comment by anthonyanjorin** [comment]
I think I've actually fixed this.  @RolandKluge can you try it out and confirm?

**Comment by SchroedingersCatIsUndead** [comment]
obsolete
