### ISSUE TITLE
QuickFix to create new AttributeCondDef in Schema

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#735]
When working in the CSP of a TGG rule,  one often wants to use an attribute condition that doesn't exist yet just by writing its name, and then using a quick fix to create a stub in the schema for a corresponding attribute condition definition.  That would be really a nice quick fix!

**Comment by RolandKluge** [comment]
This issue was moved to eMoflon/emoflon-tool#52
