### ISSUE TITLE
[TGG MOSL] Convert Vis TGGs to MOSL

### ISSUE THREAD

**Issue by erhanleblebici** [eMoflon/emoflon#741]
at least two things are to be considered for that:

- Vis. TGGs have post processing immediately after rule application. This is not supported in our textual syntax.

- A first attempt to convert a Vis. TGG did not work, probably due to technical details (such as import) that are specific to the developer workspace

**Comment by anthonyanjorin** [comment]
Just completed sdm vis.  There are 4 more vis projects remaining (tgg, tgg.runtime, sdmpatterns, and tgg.runtimepatterns)
