### ISSUE TITLE
Ecore-to-EA does not complete

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#743]
When importing one of the attached Ecore files into a fresh EAP file, only the MOCA tree instances are being generated but nothing else happens. No console output, no error log.

    09:35:00 DEBUG [ea.EnterpriseArchitectHelper::67] - Executing '"...mars_L0\plugins\org.moflon.ide.core_2.1.0.201606021008\resources\commandLineEAExport\eMoflonCommandLine.exe" -i --xmi "...\TemporarySpecification\.temp\platoon.ecore.moca.xmi" --eap "...\TemporarySpecification\TemporarySpecification.eap"'
    09:35:00 DEBUG [ea.EnterpriseArchitectCommandLineParser::78] - Start import

**Comment by SchroedingersCatIsUndead** [comment]
fixed
