### ISSUE TITLE
Scoping for FQN with the same ending doesnot work

### ISSUE THREAD

**Issue by SchroedingersCatIsUndead** [eMoflon/emoflon#745]
example:
import ".../foo1/bar.ecore"
import ".../foo2/bar.ecore"

#source {
	foo1.bar
}

#target { 
	foo2.bar
}

is needed for #689 

[SchemaViz.alpha.0.0.1.zip](https://github.com/eMoflon/emoflon/files/308669/SchemaViz.alpha.0.0.1.zip)

**Comment by anthonyanjorin** [comment]
I've now added the namespace prefix as possible, but optional completion of the fqn of a root package.
Please try it out!
