### ISSUE TITLE
Our literal expression parser does not work for numbers in ENUM literals

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#749]
I had an example with an Enum Formular, and enum literals such as C8H4O7

Our parser does not accept such enum literals and should be extended appropriately.

**Comment by RolandKluge** [comment]
Can you provide some more information? Did you try to enter an enum literal inside an attribute assignment/comparison?

**Comment by anthonyanjorin** [comment]
@erhanleblebici could you attach your minimal example?  All you need to do to reproduce the problem is have enum literals containing numbers

**Comment by erhanleblebici** [comment]
find a minimal SDM example attached to reproduce the bug.

[EnumWithNumbers_Bug.zip](https://github.com/eMoflon/emoflon/files/346252/EnumWithNumbers_Bug.zip)
