### ISSUE TITLE
Add all handbook examples and demo to a test workspace 

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#751]
Just found a bug that was only detected by the handbook example :(

**Comment by anthonyanjorin** [comment]
Well, they are already "standard workspaces", so I guess we should just add some JUnit tests.

**Comment by RolandKluge** [comment]
I have added a few tests to LearningBoxLanguage, but I don't know which problems should be covered by the unit tests, actually.

Additionally, there is now a new entry in the Test Workspaces menu (Demo +Handbook) to simplify testing.

@erhanleblebici Can you add some TGG tests as well?

**Comment by RolandKluge** [comment]
This issue was moved to eMoflon/emoflon-tool#58
