### ISSUE TITLE
TestWorkspace_TGG_0: Test failures in "TestCompanyToITIntegration"

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#758]
I built my own eMoflon using Eclipse Neon and eMoflon 2.17.0 from the Dropbox and tried to run the test workspace TGG_0. All tests in backend.languages.tggLanguage.TestCompanyToITIntegration fail repeatedly. A sample stacktrace is attached (all stack trace elements appart from the top are identical for all failures).

Attachment: [tgg_0_failure.txt](https://github.com/eMoflon/emoflon/files/410388/tgg_0_failure.txt)

**Comment by anthonyanjorin** [comment]
Fixed
