### ISSUE TITLE
link shorting website tiny.cc is down

### ISSUE THREAD

**Issue by SchroedingersCatIsUndead** [eMoflon/emoflon#760]
The link shortener tiny.cc is down. If you want to read the documentation from the eMoflon Website you get a time out. Perhaps the shortner should be replaced (i.e. [google shortner](https://goo.gl/))

**Comment by RolandKluge** [comment]
Thank you for the notification - I am strongly for returning to the good old long URLs. :-)

**Comment by RolandKluge** [comment]
Closing. #764 is a follow-up.
