### ISSUE TITLE
Refactoring: Create enum for dependency types in MetamodelLoader

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#763]

**Comment by RolandKluge** [comment]
@gervarro Do you see any arguments why switching from int-based to enum-based constants could be a problem?

**Comment by gervarro** [comment]
The constants have been intentionally defined in separate modules (USER_DEFINED vs. others). We might need 2 separate enums to implement the same functionality. I guess that this is the only issue that one has to be considered.

**Comment by RolandKluge** [comment]
OK, then we stick to the int-based mode.
