### ISSUE TITLE
The invocation of the split method in the SubMonitor class makes eMoflon unusable on older Eclipse versions

### ISSUE THREAD

**Issue by gervarro** [eMoflon/emoflon#769]
The split method in the SubMonitor class has only been recently (org.eclipse.core.resources 3.8) introduced, which means that the invocation of this method from eMoflon implicitly requires Eclipse Neon (?) to be installed. I think that enforcing users to immediately switch to the latest Eclipse version should be avoided.

**Comment by RolandKluge** [comment]
I would like to avoid an entire revert - maybe we could hide the invocation appropriately? Would continue using SubMonitor in conjunction with ```SubMonitor#newChild``` be OK from you perspective?

**Comment by anthonyanjorin** [comment]
Just my opinion:  I wouldn't mind forcing everyone to switch to Neon.  To really allow a mix of versions we would actually have to run all tests (and try out the handbook!) for multiple Eclipse versions (which we don't due to limited resources).

**Comment by RolandKluge** [comment]
This is a strong point!

However, we still could (and do) offer eMoflon for other Eclipse versions "without warranty."

I think about how to solve this.

Arguably, from the code that I saw, I think that the switch of the progress monitoring framework was necessary because it was widely misused/wrongly used (and is still at some points in the code).

**Comment by RolandKluge** [comment]
One additional note: SubMonitor#newChild does not support task cancellation - for now I would just stick to the new code and avoid reverting it.

**Comment by gervarro** [comment]
I guess you know that I am typically against forcing users to switch to the very latest version of all pieces of modules. I am that kind of user who does not want to install a new version of Java and a new version of Eclipse just to experiment with the latest eMoflon, especially if these incompatible changes happen from one day to the other. (In this case, I cannot run the code on my notebook (without installing Neon) that we developed on last Friday.)

> However, we still could (and do) offer eMoflon for other Eclipse versions "without warranty."

If "without warranty" means a nice internal Java class loader exception (that would most probably happen in the current case) or an unresolvable dependency that disables the installation of eMoflon, then I would not really like to be a user of that software.

> Would continue using SubMonitor in conjunction with SubMonitor#newChild be OK from you perspective?

Yes. That is exactly what I wanted to propose, even if SubMonitor requires extra coding effort to support task cancellation.

> Arguably, from the code that I saw, I think that the switch of the progress monitoring framework was necessary because it was widely misused/wrongly used (and is still at some points in the code).

I think that the 2 progress monitoring frameworks were different regarding their invocation patterns. At least this is my impression after reorganizing some corresponding code snippets.

**Comment by RolandKluge** [comment]
One more idea (before spending a few hours migrating to the older API methods): Is it possible to "enable" the new runtime bundle (v>=3.8), which contains ```SubMonitor#split```?

**Comment by RolandKluge** [comment]
OK, gervarro changed to the more compatible API. We will move to SubMonitor#split sometime in the future.
