### ISSUE TITLE
Outdated IDE_Vis_Modules.psf in Dropbox deployment

### ISSUE THREAD

**Issue by SchroedingersCatIsUndead** [eMoflon/emoflon#776]
This deployment has a reference to the https://dev.kom.e-technik.tu-darmstadt.de/svn/es_emoflon/trunk/org.moflon.ide.visualization.specification which doesnot exist anymore.

**Comment by RolandKluge** [comment]
@SchroedingersCatIsUndead  Does this issue still persist or did you already fix the issue?

**Comment by RolandKluge** [comment]
This issue was moved to eMoflon/emoflon-tool#64
