### ISSUE TITLE
Find a way to 'ignore' projects from exporting

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#786]
The new build process is stricter than the older one which causes problems in TestWorkspace_Misc: The MM project SDMTestSuite cannot be exported because the project ValidationTest contains errors (intentionally). We have to find a way to 'ignore' Validation Test to allow all other projects from the same EAP file to be exported.

**Comment by RolandKluge** [comment]
Temporary fix: Remove ValidationTest from EAP without committing --> TestWorkspace_Misc is green then.

**Comment by gervarro** [comment]
I think that the simplest solution would be to export this erroneous project as well but to block the execution of the corresponding RepositoryBuilder (in a later phase by using the RepositoryBuilder triggers), which actually performs the SDM validation.

**Comment by RolandKluge** [comment]
The problem actually already occurs when running the MetamodelBuilder (the error marker is on the MOCA tree file).

**Comment by RolandKluge** [comment]
OK, your solution was correct. I added P/ValidationTest to TestWorkspace_Misc and disabled all triggers in .project
