### ISSUE TITLE
Progress is 'hidden' when using the new build process

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#789]
When experimenting with the new build process, I often get the impression that everything is already complete, but in the background, jobs are still running. We should check how to report progress appropriately.

**Comment by gervarro** [comment]
I think I know what you mean. In the current solution, the very first phase (SVN check out) is performed as a user job, which is explicitly shown in the progress window in the foreground, and all the later phases are carried out as background jobs, which are only shown in the progress view. However, if all the phases were foreground jobs, then the progress window would pop up before each phase and disappear after the phase, which would be probably as disturbing as the current process. I support any better solutions, if such a solution can be implemented in a feasible way.

**Comment by RolandKluge** [comment]
OK, I solved it this way:
- Using WorkspaceInstaller, all jobs run in background
- Using one of the Hammers, all jobs run as user

See if this helps...
