### ISSUE TITLE
Use the Eclipse marketplace

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#802]
The latest and coolest way to install an Eclipse plugin is to drag and drop a "button" from a website onto a running instance of Eclipse.   No idea how this works, but it has something to do with the Eclipse marketplace.  Perhaps we should some time in the future move from our old school update sites to this?

**Comment by RolandKluge** [comment]
Does not seem to be too difficult but I would wait until eMoflon has moved to GitHub completely:

https://marketplace.eclipse.org/quickstart

**Comment by RolandKluge** [comment]
This issue was moved to eMoflon/emoflon-tool#78
