### ISSUE TITLE
Remove [additional dependency / addition gen packages] option if it is obsolete

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#804]
If we are now ignoring these entries please remove them (or close this issue if they are still being used).

**Comment by RolandKluge** [comment]
@gervarro Do you see any chance that we will need this in the future? Otherwise, I will kill it.

**Comment by gervarro** [comment]
These options are not ignored, as they might still be needed to be able to use external metamodels (if standard procedures fail). The new build process prefers the use of the file-based metamodel (even in case of deployed plugins) over the generated one in the package registry.

I would not remove this feature, as this provides more flexibility in some cases.
