### ISSUE TITLE
Caching not working for visualisation of abstract rules

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#809]
To reproduce:

Open an abstract rule in the TGG editor, and make sure "do not flatten refinements" is *not* chosen.

If you now move the cursor around in the file, you'll notice that the visualisation is being re-generated every time.  For all other visualisations, a cache is used to avoid this.  The cache is only invalidated when the editor is saved.

Using a cache is important for two reasons: (1) it keeps the picture stable (now its jumping about), and (2) for large patterns dot takes a while to regenerate the picture.

**Comment by anthonyanjorin** [comment]
Cache is also not working or not being used for the overview of all rules (visualisation for  schema.tgg)

**Comment by RolandKluge** [comment]
Migrated manually to https://github.com/eMoflon/emoflon-tool/issues/88
