### ISSUE TITLE
no-auto option for IntegrationBuilder doesn't seem to be working

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#810]
Even though I have disabled the IntegrationBuilder for auto-builds (and I see a nice [no-auto] label on the project), code is still generated when I save .tgg files.  I don't seem to notice any difference at all in the builder behaviour...

**Comment by RolandKluge** [comment]
This is strange - apparently it worked some time ago, but indeed it does not working now.

One issue that I find annoying is that (e.g.,) cspcodeadapter is build due to being a recursive dependency of another project, which is auto-built.

**Comment by RolandKluge** [comment]
This issue was moved to eMoflon/emoflon-tool#82
