### ISSUE TITLE
Code generator is deleting .gitignore in /gen folder

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#811]
It is sometimes nice to have a .gitignore in /gen so git automatically ignores all generated files.

The code generator seems to be deleting .gitignore files right now so it is impossible to do this anymore.

**Comment by RolandKluge** [comment]
My currently prefered best practice is to place one .gitignore files in the project root and to use something like /gen/* to ignore alle contents of /gen.

Using eMoflon 2.18.0 or later should generate such a .gitignore file for fresh projects.
